# Generated by Django 3.1.2 on 2020-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
