# Generated by Django 3.1.2 on 2020-10-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0002_auto_20201030_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='newer', max_length=128),
            preserve_default=False,
        ),
    ]
