# Generated by Django 3.0 on 2020-11-01 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phaseone', '0001_initial'),
        ('bogs', '0003_person_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phaseone.MessageForm')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.Group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(through='bogs.Messageship', to='phaseone.MessageForm'),
        ),
    ]
