# Generated by Django 3.1.2 on 2020-12-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0004_auto_20201101_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='messages',
        ),
        migrations.DeleteModel(
            name='Messageship',
        ),
    ]
