# Generated by Django 3.1.4 on 2020-12-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0007_group_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Token_key',
            field=models.CharField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
