# Generated by Django 3.1.2 on 2020-12-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0008_person_token_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('priority', models.CharField(choices=[('1', 'Very Important'), ('2', 'Important'), ('3', 'Okay')], max_length=2)),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('seen', models.ManyToManyField(through='bogs.Message_seen', to='bogs.Person')),
            ],
        ),
        migrations.AddField(
            model_name='message_seen',
            name='form2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.messageform'),
        ),
        migrations.AddField(
            model_name='message_seen',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(through='bogs.Messageship', to='bogs.MessageForm'),
        ),
        migrations.AlterField(
            model_name='messageship',
            name='form2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.messageform'),
        ),
    ]
