# Generated by Django 3.1.2 on 2020-12-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0009_auto_20201205_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageform',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='messageship',
            name='form2',
        ),
        migrations.RemoveField(
            model_name='messageship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invite_reason',
        ),
        migrations.AddField(
            model_name='group',
            name='bool',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='grp_name',
            field=models.CharField(default='1', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message_seen',
        ),
        migrations.DeleteModel(
            name='MessageForm',
        ),
        migrations.DeleteModel(
            name='Messageship',
        ),
    ]
