# Generated by Django 3.1.2 on 2020-12-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0010_auto_20201207_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForm',
            fields=[
                ('priority', models.CharField(choices=[('1', 'Very Important'), ('2', 'Important'), ('3', 'Okay')], max_length=2)),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('printer', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
    ]
