# Generated by Django 3.1.2 on 2020-12-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0011_messageform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messageship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.messageform')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.group')),
            ],
        ),
    ]
