# Generated by Django 3.1.2 on 2020-12-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0012_messageship'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(through='bogs.Messageship', to='bogs.MessageForm'),
        ),
    ]
