# Generated by Django 3.0 on 2020-12-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0013_group_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.MessageForm')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.Person')),
            ],
        ),
        migrations.AddField(
            model_name='messageform',
            name='seen',
            field=models.ManyToManyField(through='bogs.Message_seen', to='bogs.Person'),
        ),
    ]
