# Generated by Django 3.1.4 on 2020-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0018_auto_20201208_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_seen',
            name='form2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bogs.messageform', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='message_seen',
            unique_together=set(),
        ),
    ]
