# Generated by Django 3.1.4 on 2020-12-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogs', '0020_auto_20201208_1820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message_seen',
            unique_together={('person', 'form2')},
        ),
    ]
